import type { Address } from 'viem'

export const RIALO_TEMPLE_ADDRESS = (
  import.meta.env.VITE_RIALO_TEMPLE_ADDRESS || '0x0e5b996F56df97917289b2552A843620f9E88A60'
) as Address

export const RIALO_TEMPLE_ABI = [
  {
    inputs: [
      { internalType: 'string', name: 'username', type: 'string' },
      { internalType: 'string', name: 'xHandle', type: 'string' },
    ],
    name: 'sealProfile',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'hasProfile',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'getProfile',
    outputs: [
      {
        components: [
          { internalType: 'string', name: 'username', type: 'string' },
          { internalType: 'string', name: 'xHandle', type: 'string' },
          { internalType: 'uint256', name: 'sealedAt', type: 'uint256' },
          { internalType: 'bool', name: 'isSealed', type: 'bool' },
        ],
        internalType: 'struct RialoTempleGrialo.Profile',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'getUser',
    outputs: [
      {
        components: [
          { internalType: 'string', name: 'username', type: 'string' },
          { internalType: 'string', name: 'xHandle', type: 'string' },
          { internalType: 'bool', name: 'profileSealed', type: 'bool' },
          { internalType: 'uint256', name: 'sealedAt', type: 'uint256' },
          { internalType: 'uint256', name: 'totalSpins', type: 'uint256' },
          { internalType: 'uint256', name: 'totalPts', type: 'uint256' },
          { internalType: 'uint256', name: 'currentStreak', type: 'uint256' },
          { internalType: 'uint256', name: 'bestStreak', type: 'uint256' },
          { internalType: 'uint256', name: 'lastSpinAt', type: 'uint256' },
          { internalType: 'uint8', name: 'bestTier', type: 'uint8' },
          { internalType: 'bool', name: 'spinReady', type: 'bool' },
          { internalType: 'uint256', name: 'waitTime', type: 'uint256' },
        ],
        internalType: 'struct RialoTempleGrialo.UserView',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'spinGrialo',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'spinId', type: 'uint256' },
          { internalType: 'uint8', name: 'tier', type: 'uint8' },
          { internalType: 'uint256', name: 'pts', type: 'uint256' },
          { internalType: 'uint256', name: 'streakAfterSpin', type: 'uint256' },
          { internalType: 'uint256', name: 'timestamp', type: 'uint256' },
        ],
        internalType: 'struct RialoTempleGrialo.SpinResult',
        name: 'result',
        type: 'tuple',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'canSpin',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'timeUntilNextSpin',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'nextSpinAt',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'getStats',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'totalSpins', type: 'uint256' },
          { internalType: 'uint256', name: 'totalPts', type: 'uint256' },
          { internalType: 'uint256', name: 'currentStreak', type: 'uint256' },
          { internalType: 'uint256', name: 'bestStreak', type: 'uint256' },
          { internalType: 'uint256', name: 'lastSpinAt', type: 'uint256' },
          { internalType: 'uint8', name: 'bestTier', type: 'uint8' },
        ],
        internalType: 'struct RialoTempleGrialo.Stats',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'getLatestSpin',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'spinId', type: 'uint256' },
          { internalType: 'uint8', name: 'tier', type: 'uint8' },
          { internalType: 'uint256', name: 'pts', type: 'uint256' },
          { internalType: 'uint256', name: 'streakAfterSpin', type: 'uint256' },
          { internalType: 'uint256', name: 'timestamp', type: 'uint256' },
        ],
        internalType: 'struct RialoTempleGrialo.SpinResult',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'getSpinHistory',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'spinId', type: 'uint256' },
          { internalType: 'uint8', name: 'tier', type: 'uint8' },
          { internalType: 'uint256', name: 'pts', type: 'uint256' },
          { internalType: 'uint256', name: 'streakAfterSpin', type: 'uint256' },
          { internalType: 'uint256', name: 'timestamp', type: 'uint256' },
        ],
        internalType: 'struct RialoTempleGrialo.SpinResult[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'getSpinHistoryLength',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint8', name: 'tier', type: 'uint8' }],
    name: 'tierName',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint8', name: 'tier', type: 'uint8' }],
    name: 'boxName',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint8', name: 'tier', type: 'uint8' }],
    name: 'grialoText',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint8', name: 'tier', type: 'uint8' },
      { internalType: 'uint256', name: 'streak', type: 'uint256' },
    ],
    name: 'pointsPreview',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'limit', type: 'uint256' }],
    name: 'getTopByPts',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'user', type: 'address' },
          { internalType: 'string', name: 'username', type: 'string' },
          { internalType: 'string', name: 'xHandle', type: 'string' },
          { internalType: 'uint256', name: 'totalPts', type: 'uint256' },
          { internalType: 'uint256', name: 'totalSpins', type: 'uint256' },
          { internalType: 'uint256', name: 'bestStreak', type: 'uint256' },
          { internalType: 'uint8', name: 'bestTier', type: 'uint8' },
        ],
        internalType: 'struct RialoTempleGrialo.LeaderboardEntry[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'limit', type: 'uint256' }],
    name: 'getTopByStreak',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'user', type: 'address' },
          { internalType: 'string', name: 'username', type: 'string' },
          { internalType: 'string', name: 'xHandle', type: 'string' },
          { internalType: 'uint256', name: 'totalPts', type: 'uint256' },
          { internalType: 'uint256', name: 'totalSpins', type: 'uint256' },
          { internalType: 'uint256', name: 'bestStreak', type: 'uint256' },
          { internalType: 'uint8', name: 'bestTier', type: 'uint8' },
        ],
        internalType: 'struct RialoTempleGrialo.LeaderboardEntry[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getPlayerCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'start', type: 'uint256' },
      { internalType: 'uint256', name: 'limit', type: 'uint256' },
    ],
    name: 'getPlayers',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'spinId', type: 'uint256' },
      { indexed: false, internalType: 'uint8', name: 'tier', type: 'uint8' },
      { indexed: false, internalType: 'string', name: 'tierName', type: 'string' },
      { indexed: false, internalType: 'string', name: 'boxName', type: 'string' },
      { indexed: false, internalType: 'uint256', name: 'pts', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'streakAfterSpin', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'totalPts', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
    ],
    name: 'GrialoSpun',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'origin', type: 'string' },
      { internalType: 'string', name: 'imageUrl', type: 'string' },
      { internalType: 'uint8', name: 'rating', type: 'uint8' },
      { internalType: 'string', name: 'reviewText', type: 'string' },
    ],
    name: 'submitFoodReview',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: 'title', type: 'string' },
      { internalType: 'string', name: 'imdbUrl', type: 'string' },
      { internalType: 'uint8', name: 'rating', type: 'uint8' },
      { internalType: 'string', name: 'reviewText', type: 'string' },
    ],
    name: 'submitFilmReview',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'offset', type: 'uint256' },
      { internalType: 'uint256', name: 'limit', type: 'uint256' },
    ],
    name: 'getReviews',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'enum RialoTemple.ReviewCategory', name: 'category', type: 'uint8' },
          { internalType: 'address', name: 'reviewer', type: 'address' },
          { internalType: 'string', name: 'title', type: 'string' },
          { internalType: 'string', name: 'originOrImdb', type: 'string' },
          { internalType: 'string', name: 'imageUrl', type: 'string' },
          { internalType: 'uint8', name: 'rating', type: 'uint8' },
          { internalType: 'string', name: 'reviewText', type: 'string' },
          { internalType: 'uint256', name: 'timestamp', type: 'uint256' },
        ],
        internalType: 'struct RialoTemple.Review[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'enum RialoTemple.ReviewCategory', name: 'category', type: 'uint8' },
      { internalType: 'uint256', name: 'offset', type: 'uint256' },
      { internalType: 'uint256', name: 'limit', type: 'uint256' },
    ],
    name: 'getReviewsByCategory',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'enum RialoTemple.ReviewCategory', name: 'category', type: 'uint8' },
          { internalType: 'address', name: 'reviewer', type: 'address' },
          { internalType: 'string', name: 'title', type: 'string' },
          { internalType: 'string', name: 'originOrImdb', type: 'string' },
          { internalType: 'string', name: 'imageUrl', type: 'string' },
          { internalType: 'uint8', name: 'rating', type: 'uint8' },
          { internalType: 'string', name: 'reviewText', type: 'string' },
          { internalType: 'uint256', name: 'timestamp', type: 'uint256' },
        ],
        internalType: 'struct RialoTemple.Review[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getTotals',
    outputs: [
      { internalType: 'uint256', name: 'totalUsers', type: 'uint256' },
      { internalType: 'uint256', name: 'totalReviews', type: 'uint256' },
      { internalType: 'uint256', name: 'balance', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const

export const ARC_CHAIN = {
  id: 5042002,
  name: 'Arc Testnet',
  nativeCurrency: { name: 'USDC', symbol: 'USDC', decimals: 18 },
  rpcUrls: { default: { http: ['https://rpc.testnet.arc.network'] } },
  blockExplorers: { default: { name: 'Arcscan', url: 'https://testnet.arcscan.app' } },
  testnet: true,
} as const
